# Generated by Django 3.0.2 on 2020-02-16 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('link', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('nutriscore', models.CharField(max_length=2)),
                ('mini_image', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('nutriments', models.TextField(null=True)),
                ('category_id', models.ManyToManyField(to='offapi.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='offapi.Product')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='offapi.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product saved',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(related_name='productes', to='offapi.Store'),
        ),
    ]
