# Generated by Django 3.0.2 on 2020-01-14 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('link', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('nutriscore', models.CharField(max_length=2)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offapi.Category')),
                ('stores', models.ManyToManyField(related_name='productes', to='offapi.Store')),
            ],
        ),
    ]
