# Generated by Django 3.0.2 on 2020-01-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mini_image',
            field=models.TextField(null=True),
        ),
    ]
