# Generated by Django 3.0.2 on 2020-01-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offapi', '0002_product_mini_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
