# Generated by Django 3.0.2 on 2020-01-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200113_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(related_name='stores', to='blog.Product'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='StoreProduct',
        ),
    ]
